apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: chainlink 
  namespace: future-oracle 
  labels:
    app: chainlink
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: chainlink
  serviceName: chainlink
  template:
    metadata:
      name: chainlink
      labels:
        app: chainlink
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: oracle 
          image: "parity/parity:v2.5.2-beta"
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          args:
          - "--chain=chainlink"
          - "--base-path=/chainlink-data"
          - "--db-path=/chainlink-data/chains" 
          - "--keys-path=/chainlink-data/keys"
          - "--websocket-port=8546"
          - "--websocket-interface=0.0.0.0"
          - "--websocket-apis=web3,eth,net,rpc,parity"
          - "--jsonrpc-hosts=all"
          - "--no-ancient-blocks"
          - "--no-serve-light"
          - "--max-peers=250"
          - "--snapshot-peers=50"
          ports:
            - containerPort: 8546
              protocol: TCP
              name: websocket
            - containerPort: 443
              protocol: TCP
              name: https
          readinessProbe:
            httpGet:
              port: 8545
              path: /api/health
            initialDelaySeconds: 4500 
            periodSeconds: 300
          livenessProbe:
            tcpSocket:
              port: 8545
            initialDelaySeconds: 4500 
            periodSeconds: 300
          volumeMounts:
            - name: chainlink-config
              mountPath: /chainlink-config
              readOnly: true
            - name: chainlink-data
              mountPath: /chainlink-data
    volumes:
      - name: chainlink-config
        secret:
          secretName: chainlink-config
  volumeClaimTemplates:
    - metadata:
        name: chainlink-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "chainlink-ssd"
        resources:
          requests:
            storage: 50Gi
