apiVersion: v1
kind: Service
metadata:
  labels:
    app: chainlink-master 
  name: chainlink-master
  namespace: future-oracle 
  annotations:
    cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'
spec:
  selector:
    app: chainlink-master
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 80
  - name: websocket
    port: 8546
    protocol: TCP
    targetPort: 8546
  type: NodePort 
  sessionAffinity: ClientIP
